POST http://localhost:8080/tasks
Content-Type: application/json

{"title":"a","description":"aaa","priority": 2}

###

POST http://localhost:8080/tasks
Content-Type: application/json

{"title":"s","description":"ddd"}

###
GET http://localhost:8080/tasks
Accept: application/json

###
GET http://localhost:8080/tasks/2
Accept: application/json

###
GET http://localhost:8080/tasks/7
Accept: application/json

###
DELETE http://localhost:8080/tasks/6

###
PUT http://localhost:8080/tasks/4
Content-Type: application/json

{"title":"e","description":"eee","priority":  3}

###
PATCH http://localhost:8080/tasks/3
Content-Type: application/json

{"title": "w"}

###
PATCH http://localhost:8080/tasks/1
Content-Type: application/json

{"description":  " j "}

###
PATCH http://localhost:8080/tasks/3
Content-Type: application/json

{}

###
PATCH http://localhost:8080/tasks/3
Content-Type: application/json

{"description":  " "}

###
PUT http://localhost:8080/tasks/1
Content-Type: application/json

{"title":"d","description":""}

###
PUT http://localhost:8080/tasks/1
Content-Type: application/json

{"title":"","description":"k"}

###
PUT http://localhost:8080/tasks/1
Content-Type: application/json

{"title":"","description":""}